// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmsC37d_EwNRawFXEgzhLCewzsL5Q5_WQ',
    appId: '1:204261758734:web:13a6414348aafc63d8e95f',
    messagingSenderId: '204261758734',
    projectId: 'connectify-lucky',
    authDomain: 'connectify-lucky.firebaseapp.com',
    storageBucket: 'connectify-lucky.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFTJj4R8HMzu6dJdQDqMoF3mRccf3o_Ak',
    appId: '1:204261758734:android:bd42c639378e6ec0d8e95f',
    messagingSenderId: '204261758734',
    projectId: 'connectify-lucky',
    storageBucket: 'connectify-lucky.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC10XcecJ_2NJAcequ0kXM5BGNCuKDbpbU',
    appId: '1:204261758734:ios:29847eee88881903d8e95f',
    messagingSenderId: '204261758734',
    projectId: 'connectify-lucky',
    storageBucket: 'connectify-lucky.firebasestorage.app',
    iosBundleId: 'com.example.connectify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC10XcecJ_2NJAcequ0kXM5BGNCuKDbpbU',
    appId: '1:204261758734:ios:29847eee88881903d8e95f',
    messagingSenderId: '204261758734',
    projectId: 'connectify-lucky',
    storageBucket: 'connectify-lucky.firebasestorage.app',
    iosBundleId: 'com.example.connectify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmsC37d_EwNRawFXEgzhLCewzsL5Q5_WQ',
    appId: '1:204261758734:web:522b5c932f3f168fd8e95f',
    messagingSenderId: '204261758734',
    projectId: 'connectify-lucky',
    authDomain: 'connectify-lucky.firebaseapp.com',
    storageBucket: 'connectify-lucky.firebasestorage.app',
  );
}
